Update dotfiles and scripts

diff --git a/install b/install
--- a/install
+++ b/install
@@ -15,52 +15,61 @@ sudo chmod +x install-symlinks
 ./install-symlinks
 
 # Python
-pip3 install --upgrade pip
-pip3 install neovim
+echo "Installing Python modules for NeoVim"
+pip3 install --upgrade pip >/dev/null 2>&1 || echo "Failed to upgrade pip"
+pip3 install neovim >/dev/null 2>&1 || echo "Failed to install neovim python plugin"
 
 # Zplug
 if [ ! -d ~/.zplug ]; then
+  echo "Downloading ZPlug"
   curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh| zsh
   chmod -R 755 ~/.zplug
 fi
 
 # Make files in ~/bin executable
+echo "Setting executable permissions on ~/bin folder"
 chmod +x ~/bin/*
 
 # Install Neovim plugins
-nvim --headless +UpdateRemotePlugins +qall
-nvim --headless +PlugInstall +qall
+echo "Installing NeoVim plugins"
+nvim --headless +UpdateRemotePlugins +qall >/dev/null 2>&1
+nvim --headless +PlugInstall +qall >/dev/null 2>&1
 
 # Postgres
-# Assumes a postgres server is running somewhere
-# with default credentials (postgres/postgres)
 # Afterwards you should be able to connect using just 'psql'
-psql -U postgres -tc "SELECT 1 FROM pg_roles WHERE rolname='$USER'" | grep -q 1 || psql -U postgres -c "CREATE USER $USER WITH SUPERUSER"
-psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = '$USER'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE $USER"
+echo "Setting default users and permissions for PostgresQL"
+sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres'" >/dev/null 2>&1 || echo "Failed to set password for postgres user"
+sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='$USER'" | grep -q 1 || sudo -u postgres psql -c "CREATE USER $USER WITH SUPERUSER" >/dev/null 2>&1
+sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = '$USER'" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE $USER" >/dev/null 2>&1
 
 # Asdf version manager
 if [ ! -d ~/.asdf ]; then
-  git clone https://github.com/asdf-vm/asdf.git "${HOME}/.asdf" --branch v0.4.1
+  echo "Installing ASDF version manager 0.4.1"
+  git clone https://github.com/asdf-vm/asdf.git "${HOME}/.asdf" --branch v0.4.1 >/dev/null 2>&1 || echo "Failed to clone asdf into ~/.asdf"
 else
-  pushd ~/.asdf
-  git fetch && git checkout v0.4.1
-  popd
+  echo "Updating ASDF version manager"
+  pushd ~/.asdf >/dev/null 2>&1
+  git fetch >/dev/null 2>&1 && git checkout v0.4.1 >/dev/null 2>&1 || echo "Failed to update ASDF"
+  popd >/dev/null 2>&1
 fi
 
 source ~/.asdf/asdf.sh
 
 # Node
-asdf plugin-list | grep -q nodejs || asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
-bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring # Node.js team's PGP keys
-asdf list nodejs | grep -q 8.4.0 || asdf install nodejs 8.4.0
-asdf global nodejs 8.4.0
+echo "Installing Node"
+asdf plugin-list | grep -q nodejs || asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git >/dev/null 2>&1 || echo "Failed to fetch ASDF node plugin"
+bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring >/dev/null 2>&1 || echo "Failed to add NodeJS GPG keys to keyring"
+asdf list nodejs | grep -q 8.4.0 || asdf install nodejs 8.4.0 >/dev/null 2>&1 || echo "Failed to install NodeJS"
+asdf global nodejs 8.4.0 || echo "Failed to set global NodeJS version"
 
 # Ruby
-asdf plugin-list | grep -q ruby || asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
-asdf list ruby | grep -q 2.5.0 || asdf install ruby 2.5.0
-asdf global ruby 2.5.0
+echo "Installing Ruby"
+asdf plugin-list | grep -q ruby || asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git >/dev/null 2>&1 || echo "Failed to fetch ASDF ruby plugin"
+asdf list ruby | grep -q 2.5.0 || asdf install ruby 2.5.0 >/dev/null 2>&1 || echo "Failed to install Ruby"
+asdf global ruby 2.5.0 || echo "Failed to set global Ruby version"
 
 # Elixir
-asdf plugin-list | grep -q elixir || asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
-asdf list elixir | grep -q 1.6.1 || asdf install elixir 1.6.1
-asdf global elixir 1.6.1
+echo "Installing Elixir"
+asdf plugin-list | grep -q elixir || asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git >/dev/null 2>&1 || echo "Failed to fetch ASDF elixir plugin"
+asdf list elixir | grep -q 1.6.1 || asdf install elixir 1.6.1 >/dev/null 2>&1 || echo "Failed to install Elixir"
+asdf global elixir 1.6.1 || echo "Failed to set global Elixir version"
diff --git a/install-apt-wsl b/install-apt-wsl
--- a/install-apt-wsl
+++ b/install-apt-wsl
@@ -1,98 +1,121 @@
 #!/usr/bin/env bash
 set -e
 
+# Disable sudo prompt
+echo "Disabling prompt for sudo"
+if ! sudo grep -q "%sudo[[:space:]]ALL=(ALL:ALL) NOPASSWD:ALL" /etc/sudoers >/dev/null 2>&1
+then
+  echo "%sudo ALL=(ALL:ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers >/dev/null 2>&1 || echo "Failed to edit sudoers file"
+fi
+
 # Neovim Repo
-sudo add-apt-repository ppa:neovim-ppa/stable -y
+echo "Adding PPA for NeoVim"
+sudo add-apt-repository ppa:neovim-ppa/stable -y >/dev/null 2>&1 || echo "Failed to add NeoVim PPA"
 
 # Yarn Repo
-curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
-echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
+echo "Adding repo for Yarn"
+curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - >/dev/null 2>&1 || echo "Failed to add Yarn GPG key"
+echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list >/dev/null 2>&1 || echo "Failed to add yarn repo"
 
 # Keybase
+echo "Installing Keybase"
 TEMP_KBS="$(mktemp)"
-wget -O "$TEMP_KBS" "https://prerelease.keybase.io/keybase_amd64.deb"
-sudo dpkg --skip-same-version -i "$TEMP_KBS"
-sudo apt-get -y install -f
-run_keybase > /dev/null 2>&1
+wget -O "$TEMP_KBS" "https://prerelease.keybase.io/keybase_amd64.deb" >/dev/null 2>&1 || echo "Failed to download keybase"
+sudo dpkg --skip-same-version -i "$TEMP_KBS" >/dev/null 2>&1 || echo "Failed to install Keybase"
+sudo apt-get -y install -f >/dev/null 2>&1 || echo "Failed to install Keybase deps"
+run_keybase > /dev/null 2>&1 || echo "Failed to start Keybase"
 
 # Erlang Repo
+echo "Installing Erlang"
 TEMP_ERL="$(mktemp)"
-wget -O "$TEMP_ERL" "https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb"
-sudo dpkg --skip-same-version -i "$TEMP_ERL"
+wget -O "$TEMP_ERL" "https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb" >/dev/null 2>&1 || echo "Failed to download Erlang"
+sudo dpkg --skip-same-version -i "$TEMP_ERL" >/dev/null 2>&1 || echo "Failed to install Erlang"
 rm -f "$TEMP_ERL"
 
 # Update apt sources
-sudo apt-get -y update
+echo "Updating apt sources"
+sudo apt-get -qq -y update
 
 # Get package list to install
-PKG_ALL=`echo "$a" | sed '/^||ALL||$/,/^||ENDALL||$/!d;//d' packages`
-PKG_APT=`echo "$a" | sed '/^||APT||$/,/^||ENDAPT||$/!d;//d' packages`
+echo "Getting packages to install"
+PKG_ALL=`echo "$a" | sed '/^||ALL||$/,/^||ENDALL||$/!d;//d' packages` >/dev/null 2>&1 || echo "Failed to load universal packages to install"
+PKG_APT=`echo "$a" | sed '/^||APT||$/,/^||ENDAPT||$/!d;//d' packages` >/dev/null 2>&1 || echo "Failed to load apt packages to install"
 PACKAGES="$PKG_ALL $PKG_APT"
 
 # Install packages
-sudo apt-get -y install $(echo $PACKAGES | tr '\n' ' ')
+echo "Installing packages"
+sudo apt-get -qq -y install $(echo $PACKAGES | tr '\n' ' ') || echo "Failed to install some packages"
 
-# Set default shell
-sudo chsh -s /bin/zsh
-
-# Set neovim as default
-sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
-echo 0 | sudo update-alternatives --config vi
-sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
-echo 0 | sudo update-alternatives --config vim
-sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
-echo 0 | sudo update-alternatives --config editor
+# Start postgres if it was installed
+if service --status-all 2>&1 | grep -Fq 'postgresql'
+then
+  echo "Starting PostgresQL"
+  sudo service postgresql start >/dev/null 2>&1 || echo "Failed to start PostgresQL"
+fi
 
 # WSL Helpers symlinks
+echo "Symlinking WSL specific files"
 mkdir -p ~/bin
 
+echo "Linking Chromedriver"
 sudo rm -rf ~/bin/chromedriver > /dev/null 2>&1
 ln -sf $PWD/dotfiles/bin/chromedriver ~/bin/chromedriver
 
+echo "Linking MSBuild"
 sudo rm -rf ~/bin/msbuild > /dev/null 2>&1
 ln -sf $PWD/dotfiles/bin/msbuild ~/bin/msbuild
 
+echo "Linking wsl-browser-bridge"
 sudo rm -rf ~/bin/wsl-browser-bridge > /dev/null 2>&1
 ln -sf $PWD/dotfiles/bin/wsl-browser-bridge ~/bin/wsl-browser-bridge
 
+echo "Linking wslpath"
 sudo rm -rf ~/bin/wslpath > /dev/null 2>&1
 ln -sf $PWD/dotfiles/bin/wslpath ~/bin/wslpath
 
 # Install stuff on the Windows-side
-pushd /mnt/c
+echo "Installing Windows programs"
+pushd /mnt/c >/dev/null 2>&1
 
-cmd.exe /c "if not exist Workspace\\Tools\\Chromedriver mkdir Workspace\\Tools\\Chromedriver"
-cmd.exe /c "if not exist Workspace\\Tools\\OmniSharp mkdir Workspace\\Tools\\OmniSharp"
-cmd.exe /c "if not exist Workspace\\Tools\\Wsltty\\bin mkdir Workspace\\Tools\\Wsltty\\bin"
+cmd.exe /c "if not exist Workspace\\Tools\\Chromedriver mkdir Workspace\\Tools\\Chromedriver" >/dev/null 2>&1 || echo "Failed to creare dir for Chromedriver"
+cmd.exe /c "if not exist Workspace\\Tools\\OmniSharp mkdir Workspace\\Tools\\OmniSharp" >/dev/null 2>&1 || echo "Failed to create dir for OmniSharp"
+cmd.exe /c "if not exist Workspace\\Tools\\Wsltty\\bin mkdir Workspace\\Tools\\Wsltty\\bin" >/dev/null 2>&1 || echo "Failed to create dir for Wsltty"
 cd /mnt/c/Workspace/Tools
 
 # Chromedriver
+echo "Downloading Chromedriver"
 TEMP_NGT="$(mktemp)"
-wget -O "$TEMP_NGT" "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe"
-mv "$TEMP_NGT" /mnt/c/Workspace/Tools/nuget.exe
-cmd.exe /c "nuget.exe install Selenium.WebDriver.ChromeDriver -ExcludeVersion"
-mv Selenium.WebDriver.ChromeDriver/driver/win32/chromedriver.exe Chromedriver/
+wget -O "$TEMP_NGT" "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" >/dev/null 2>&1 || echo "Failed to download nuget.exe"
+mv "$TEMP_NGT" /mnt/c/Workspace/Tools/nuget.exe || echo "Failed to move buget.exe to Tools folder"
+cmd.exe /c "nuget.exe install Selenium.WebDriver.ChromeDriver -ExcludeVersion" >/dev/null 2>&1 || echo "Failed to download chromedriver from nuget"
+mv Selenium.WebDriver.ChromeDriver/driver/win32/chromedriver.exe Chromedriver/ || echo "Failed to move Chromedriver to Tools folder"
 
 # OmniSharp
+echo "Downloading OmniSharp"
 TEMP_OMN="$(mktemp)"
-wget -O "$TEMP_OMN" "https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.28.0/omnisharp.http-win-x64.zip"
-mv "$TEMP_OMN" /mnt/c/Workspace/Tools/omnisharp.zip
-powershell.exe -Command "Expand-Archive -Path omnisharp.zip -DestinationPath OmniSharp -Force"
+wget -O "$TEMP_OMN" "https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.28.0/omnisharp.http-win-x64.zip" >/dev/null 2>&1 || echo "Failed to download OmniSharp"
+mv "$TEMP_OMN" /mnt/c/Workspace/Tools/omnisharp.zip || echo "Failed to move OmniSharp.zip to Tools folder"
+powershell.exe -Command "Expand-Archive -Path omnisharp.zip -DestinationPath OmniSharp -Force" >/dev/null 2>&1 || echo "Failed to unpack OmniSharp"
 
 # Wsltty
-sudo apt install p7zip-full p7zip-rar
+echo "Installing Wsltty"
+sudo apt-get -y install p7zip-full p7zip-rar >/dev/null 2>&1 || echo "Failed to download 7z for extracting wsltty"
 TEMP_WSL="$(mktemp -d)"
-wget -O "$TEMP_WSL/wsltty.exe" "https://github.com/mintty/wsltty/releases/download/1.8.3.2/wsltty-1.8.3.2-install.exe"
-7z e $TEMP_WSL/wsltty.exe -o/mnt/c/Workspace/Tools/Wsltty/bin cygwin1.dll cygwin-console-helper.exe mintty.exe wslbridge.exe wslbridge-backend -y
+wget -O "$TEMP_WSL/wsltty.exe" "https://github.com/mintty/wsltty/releases/download/1.8.3.2/wsltty-1.8.3.2-install.exe" >/dev/null 2>&1 || echo "Failed to download Wsltty"
+7z e $TEMP_WSL/wsltty.exe -o/mnt/c/Workspace/Tools/Wsltty/bin cygwin1.dll cygwin-console-helper.exe mintty.exe wslbridge.exe wslbridge-backend -y >/dev/null 2>&1 || echo "Failed to extract Wsltty"
 
 # Cleanup
+echo "Cleaning up"
 rm -r $TEMP_WSL
 rm nuget.exe
 rm -r Selenium.WebDriver.ChromeDriver
 rm omnisharp.zip
 
-popd
+popd >/dev/null 2>&1
 
+echo "Copying Wsltty dotfiles to Wsltty folder"
 cp dotfiles/wsltty/* /mnt/c/Workspace/Tools/Wsltty -r
-powershell.exe -Command 'robocopy "C:\Workspace\Tools\Wsltty" "$env:APPDATA\Microsoft\Windows\Start Menu\Programs" wsl-terminal.lnk'
-powershell.exe -Command '(New-Object -ComObject shell.application).Namespace("$env:APPDATA\Microsoft\Windows\Start Menu\Programs").parsename("wsl-terminal.lnk").invokeverb("pintostartscreen")'
+
+echo "Creating shortcut to Wsltty on Windows Start Menu"
+powershell.exe -Command 'robocopy "C:\Workspace\Tools\Wsltty" "$env:APPDATA\Microsoft\Windows\Start Menu\Programs" wsl-terminal.lnk' >/dev/null 2>&1 || echo "Failed to copy shortcut"
+powershell.exe -Command '(New-Object -ComObject shell.application).Namespace("$env:APPDATA\Microsoft\Windows\Start Menu\Programs").parsename("wsl-terminal.lnk").invokeverb("pintostartscreen")' >/dev/null 2>&1 || echo "Failed to pin shortcut to Start Menu"
