update install-apt

diff --git a/install-apt b/install-apt
--- a/install-apt
+++ b/install-apt
@@ -20,9 +20,10 @@ then
   echo "%sudo ALL=(ALL:ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers >/dev/null 2>&1 || echo "Failed to edit sudoers file"
 fi
 
-sudo apt-get -qq -y update && sudo apt-get -y upgrade || echo "Failed to apt-update/apt-upgrade"
-sudo apt-get -y install cmake autoconf libtool libtool-bin pkg-config m4 software-properties-common libncurses5-dev >/dev/null 2>&1
-sudo apt-get -y install build-essential qt5-default libqt5webkit5-dev python-dev python3-dev python-pip python3-pip >/dev/null 2>&1
+echo "Updating apt repos and installing pre-reqs"
+sudo apt-get -qq -y update && sudo apt-get -y upgrade >/dev/null 2>&1 || echo "Failed to apt-update/apt-upgrade"
+sudo apt-get -y install unzip cmake autoconf libtool libtool-bin pkg-config m4 software-properties-common libncurses5-dev >/dev/null || echo "Failed to install pre-reqs"
+sudo apt-get -y install build-essential qt5-default libqt5webkit5-dev python-dev python3-dev python-pip python3-pip >/dev/null || echo "Failed to install pre-reqs"
 
 # Debian pre-reqs
 if [ "$DISTRO" = "Debian" ]; then
